language: cpp
compiler:
 - gcc
 - clang
before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update
install:
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libsqlite3-dev

script:
 - cmake .
 - make