os:
 - Windows Server 2012 R2
clone_depth: 1

environment:
 QTDIR: C:\Qt\5.5\msvc2013
 MINGW: C:\Qt\Tools\mingw492_32 
configuration:
 - Release
platform:
 - x86
before_build:
 - ps: cmake -DCMAKE_PREFIX_PATH=C:\Qt\5.5\msvc2013\lib\cmake .
build:
 project: MagnasTareas.sln
